// <auto-generated />
using System;
using CareLink.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareLink.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603071532_AddServicesAndRequests")]
    partial class AddServicesAndRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("CareLink.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("AiMatchScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAIRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "456 George St",
                            AiMatchScore = 0.0,
                            Category = "Food",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(7420),
                            Description = "Emergency relief assistance including food parcels, utility bills, furniture, and clothing for people in need.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "Mon-Fri 9am-5pm",
                            Phone = "02 9261 1433",
                            State = "NSW",
                            Suburb = "Sydney",
                            Tags = "food,emergency,clothing,furniture",
                            Title = "St Vincent de Paul Society",
                            Website = "https://www.vinnies.org.au"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Level 2, 323 Castlereagh St",
                            AiMatchScore = 0.0,
                            Category = "Mental Health",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Free mental health support for young people aged 12-25. Counselling, group therapy, and crisis support.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "Mon-Fri 9am-6pm",
                            Phone = "02 9114 4100",
                            State = "NSW",
                            Suburb = "Sydney",
                            Tags = "mental health,youth,counselling,crisis,anxiety,depression",
                            Title = "Headspace Mental Health Centre",
                            Website = "https://headspace.org.au"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Level 7, 580 George St",
                            AiMatchScore = 0.0,
                            Category = "Housing",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Affordable and crisis housing solutions for homeless individuals and families.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "24/7 crisis line",
                            Phone = "02 9219 2000",
                            State = "NSW",
                            Suburb = "Sydney",
                            Tags = "housing,homeless,crisis,accommodation,rent",
                            Title = "Mission Australia Housing",
                            Website = "https://www.missionaustralia.com.au"
                        },
                        new
                        {
                            Id = 4,
                            Address = "10 Parker Street",
                            AiMatchScore = 0.0,
                            Category = "Employment",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8410),
                            Description = "Employment assistance, resume support, job search coaching and skills training for disadvantaged job seekers.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "Mon-Thu 9am-4pm",
                            Phone = "02 9891 3333",
                            State = "NSW",
                            Suburb = "Parramatta",
                            Tags = "employment,jobs,resume,skills,training",
                            Title = "Sydney Community Services"
                        },
                        new
                        {
                            Id = 5,
                            Address = "323 Castlereagh St",
                            AiMatchScore = 0.0,
                            Category = "Legal",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8420),
                            Description = "Free legal advice for people who cannot afford a lawyer. Covers family law, criminal, civil, and immigration.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "Mon-Fri 9am-5pm",
                            Phone = "1300 888 529",
                            State = "NSW",
                            Suburb = "Sydney",
                            Tags = "legal,law,family,criminal,immigration,advice",
                            Title = "Legal Aid NSW",
                            Website = "https://www.legalaid.nsw.gov.au"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Online Service",
                            AiMatchScore = 0.0,
                            Category = "Health",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8420),
                            Description = "AI-powered telehealth platform connecting patients with GPs via video call. Bulk billed for concession card holders.",
                            IsAIRecommended = false,
                            IsFree = false,
                            OpeningHours = "7am-11pm daily",
                            Phone = "1300 472 882",
                            State = "All",
                            Suburb = "Australia-wide",
                            Tags = "health,GP,doctor,telehealth,bulk billing,concession",
                            Title = "GP2U Telehealth",
                            Website = "https://www.gp2u.com.au"
                        },
                        new
                        {
                            Id = 7,
                            Address = "140 Elizabeth St",
                            AiMatchScore = 0.0,
                            Category = "Food",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8420),
                            Description = "Crisis food, emergency accommodation, financial counselling, and family support programs.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "Mon-Fri 8am-8pm",
                            Phone = "02 9266 9222",
                            State = "NSW",
                            Suburb = "Sydney",
                            Tags = "food,emergency,financial,family,crisis",
                            Title = "Salvation Army Emergency Services",
                            Website = "https://www.salvationarmy.org.au"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Online / Phone",
                            AiMatchScore = 0.0,
                            Category = "Mental Health",
                            CreatedAt = new DateTime(2026, 6, 3, 7, 15, 32, 244, DateTimeKind.Utc).AddTicks(8420),
                            Description = "24/7 mental health and crisis support. AI-powered chat and phone counselling for anxiety and depression.",
                            IsAIRecommended = false,
                            IsFree = true,
                            OpeningHours = "24/7",
                            Phone = "1300 22 4636",
                            State = "All",
                            Suburb = "Australia-wide",
                            Tags = "mental health,crisis,anxiety,depression,suicide,24/7",
                            Title = "Beyond Blue Support Line",
                            Website = "https://www.beyondblue.org.au"
                        });
                });

            modelBuilder.Entity("CareLink.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NeedsDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Suburb")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
